# Generated by Django 5.0.7 on 2024-07-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endusers_loginfo',
            name='is_enduser',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='endusers_loginfo',
            name='is_seller',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
