# Generated by Django 5.0.7 on 2024-08-04 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_endusers_loginfo_is_enduser_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='endusers_loginfo',
            name='users',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='endusers_loginfo',
            name='phonenumber',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
