# Generated by Django 5.0.7 on 2024-08-16 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_endusers_loginfo_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endusers_loginfo',
            name='users',
        ),
    ]
