# Generated by Django 5.0.7 on 2024-07-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
