# Generated by Django 5.0.7 on 2024-07-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicprouctdetails',
            name='slug',
            field=models.SlugField(editable=False, max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='slug',
            field=models.SlugField(editable=False, max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='imagesm',
            name='slug',
            field=models.SlugField(editable=False, max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='slug',
            field=models.SlugField(editable=False, max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='slug',
            field=models.SlugField(editable=False, max_length=225, unique=True),
        ),
    ]
